name: Maven CI Tests with Testcontainers

on:
  workflow_dispatch:
    # branches: [ "develop_testcontainers_experimental" ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
      
    - name: Login to hub  
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build the Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/chefskiss_webapp:experimental
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
  deploy:
      runs-on: self-hosted
      needs: build
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Docker Compose Action
          run: | 
            if [ $( docker ps -a -f name=chefskiss-chefskiss_webapp-1 | wc -l ) -eq 2 ]; then
              docker compose down chefskiss_webapp
              docker compose stop chefskiss_database
            fi
            docker compose build chefskiss_webapp
            docker compose up -d
                  
