name: Maven CI Tests with Testcontainers

on:
  workflow_dispatch:
    # branches: [ "develop_testcontainers_experimental" ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    - name: Upload war artifact
      uses: actions/upload-artifact@v4
      with:
        name: chefskiss_war
        path: |
          /home/runner/work/chefsKiss/chefsKiss/target/chefsKiss-0.0.1-SNAPSHOT.war
                  
