name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Login to hub  
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/chefskiss_webapp:latest
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  deploy:
      runs-on: self-hosted
      needs: build
      steps:
        #- uses: actions/checkout@v4
        - name: Docker Compose Action
          run: | 
            if [ $( docker ps -a -f name=chefskiss-chefskiss_webapp-1 | wc -l ) -eq 2 ]; then
              docker compose down
            fi
            docker compose build chefskiss_webapp
            docker compose up -d
          # You may pin to the exact commit or the version.
          # uses: hoverkraft-tech/compose-action@802a148945af6399a338c7906c267331b39a71af
          # uses: hoverkraft-tech/compose-action@v2.0.0
          # with:
            # Relative path to compose file(s). It can be a list of files.
            # compose-file: ./docker-compose.yaml # optional, default is ./docker-compose.yml
            # Services to perform docker-compose up.
            # services: # optional
            # Additional options to pass to `docker-compose up` command.
            # up-flags: # optional, default is 
            # Additional options to pass to `docker-compose down` command.
            # down-flags: # optional, default is 
            # Additional options to pass to `docker-compose` command.
            # compose-flags: # optional, default is 
            # Current working directory
            # cwd: # optional, default is ${{ github.workspace }}

          working-directory: ${{ github.workspace }}
                  
