name: CI/CD Pipeline con Maven, Docker & Testcontainers

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build con Maven
      run: mvn -B clean package --file pom.xml

    - name: Upload war file
      uses: actions/upload-artifact@v4
      with:
        name: chefskiss_war
        retention-days: 5
        path: |
          /home/runner/work/chefsKiss/chefsKiss/target/chefsKiss-0.0.1-SNAPSHOT.war

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Download war file
      uses: actions/download-artifact@v4
      with:
        name: chefskiss_war

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: ${{ secrets.DOCKER_USERNAME }}/chefskiss_webapp:testing

    - name: Integration testing con Maven
      run: mvn -B failsafe:integration-test surefire-report:report-only --file pom.xml

    - name: Upload Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/chefskiss_webapp:latest
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Upload Surefire & Jacoco report
      uses: actions/upload-artifact@v4
      with:
        name: reports
        retention-days: 5
        path: |
          /home/runner/work/chefsKiss/chefsKiss/target/site
      
  deploy:
    runs-on: self-hosted
      
    needs: build
      
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Docker Compose Action
        run: | 
          if [ $( docker ps -f name=chefskiss-chefskiss | wc -l ) -eq 3 ]; then
            docker compose down chefskiss_webapp
            docker compose stop chefskiss_database
          fi
          docker compose build chefskiss_webapp
          docker compose up -d
      
      - name: Download Jacoco report
        uses: actions/download-artifact@v4
        with:
          name: reports
          path: ../../../../project_reports/
                  
